// Placeholder questions for RIASEC test
// In a real implementation, these would be actual RIASEC questions

const questionsData = [
    { dimension: "R1", profession: "Dessinateur projeteur", description: "Réalise des plans techniques sur ordinateur en 2D ou 3D pour construire des maisons, des machines ou des pièces." },
{ dimension: "R1", profession: "Mécanicien", description: "Démonte, répare et remonte des moteurs ou des pièces de voitures, motos ou machines." },
{ dimension: "R1", profession: "Pâtissier", description: "Prépare des gâteaux, tartes, viennoiseries en suivant des recettes précises et en respectant les temps de cuisson." },
{ dimension: "R2", profession: "Entraîneur sportif", description: "Organise des séances d’entraînement, corrige les gestes techniques et motive les sportifs." },
{ dimension: "R2", profession: "Militaire / Gendarme", description: "Patrouille, sécurise des lieux, intervient lors d’incidents ou aide en cas de catastrophe." },
{ dimension: "R2", profession: "Conducteur (voiture/camion/engin…)", description: "Conduit des véhicules pour transporter des marchandises ou des personnes, parfois sur de longues distances." },
{ dimension: "I1", profession: "Ingénieur", description: "Conçoit des objets ou des systèmes (ponts, logiciels, machines) en utilisant des calculs et des plans techniques." },
{ dimension: "I1", profession: "Programmeur informatique", description: "Écrit du code pour créer des sites web, des applications ou des jeux vidéo." },
{ dimension: "I1", profession: "Météorologue", description: "Analyse des données (température, vent, pression) pour prévoir le temps et alerter en cas de risques." },
{ dimension: "I2", profession: "Archéologue", description: "Fouille des terrains, nettoie et étudie des objets anciens pour comprendre l’histoire." },
{ dimension: "I2", profession: "Chercheur scientifique", description: "Réalise des expériences en laboratoire pour découvrir ou améliorer des matériaux, des médicaments ou des technologies." },
{ dimension: "I2", profession: "Océanographe", description: "Étudie les fonds marins, les courants et les animaux marins à bord de bateaux ou en laboratoire." },
{ dimension: "A1", profession: "Architecte d'intérieur", description: "Choisit les meubles, les couleurs et l’agencement d’un espace pour le rendre fonctionnel et esthétique." },
{ dimension: "A1", profession: "Illustrateur d'ouvrages", description: "Dessine des personnages, des décors ou des scènes pour des livres, BD ou manuels scolaires." },
{ dimension: "A1", profession: "Styliste", description: "Crée des modèles de vêtements, sélectionne les tissus et supervise la fabrication avec les couturiers." },
{ dimension: "A2", profession: "Critique artistique", description: "Regarde des films, spectacles ou expositions et écrit des articles pour donner son avis argumenté." },
{ dimension: "A2", profession: "Conservateur du patrimoine", description: "Organise des expositions, restaure des œuvres et veille à leur conservation dans les musées." },
{ dimension: "A2", profession: "Directeur de communication", description: "Prépare des messages, des affiches ou des vidéos pour que l’entreprise soit bien comprise et" },
{ dimension: "S1", profession: "Infirmier", description: "Soigne les patients, fait des pansements, donne des médicaments et rassure les personnes malades." },
{ dimension: "S1", profession: "Psychologue", description: "Écoute les personnes en difficulté, pose des questions et les aide à comprendre leurs émotions." },
{ dimension: "S1", profession: "Kinésithérapeute", description: "Fait faire des exercices aux patients pour qu’ils retrouvent leurs mouvements après une blessure." },
{ dimension: "S2", profession: "Professeur", description: "Prépare des cours, explique les leçons et aide les élèves à progresser." },
{ dimension: "S2", profession: "CPE", description: "Surveille les élèves, gère les conflits et communique avec les familles." },
{ dimension: "S2", profession: "Coach", description: "Aide une personne à atteindre ses objectifs en discutant et en proposant des méthodes" },
{ dimension: "E1", profession: "Manager d’équipe", description: "Organise le travail d’une équipe, répartit les tâches et motive les salariés pour atteindre les objectifs." },
{ dimension: "E1", profession: "Organisateur d’événements", description: "Choisit le lieu, contacte les prestataires et coordonne les activités pour que l’événement se déroule bien." },
{ dimension: "E1", profession: "Entrepreneur", description: "Crée une entreprise, décide des produits à vendre et gère les finances et la communication." },
{ dimension: "E2", profession: "Influenceur / Youtuber", description: "Crée des vidéos ou des posts pour présenter des produits ou des idées à son public." },
{ dimension: "E2", profession: "Vendeur / Vendeuse", description: "Accueille les clients, présente les produits et encaisse les achats." },
{ dimension: "E2", profession: "Agent immobilier", description: "Fait visiter des logements, explique les caractéristiques et aide à négocier le prix." },
{ dimension: "C1", profession: "Comptable", description: "Vérifie les dépenses et les recettes, prépare les bilans et s’assure que les comptes sont justes." },
{ dimension: "C1", profession: "Notaire", description: "Rédige des contrats officiels (vente de maison, mariage, testament) et les fait signer." },
{ dimension: "C1", profession: "Secrétaire", description: "Organise les rendez-vous, répond au téléphone et classe les documents." },
{ dimension: "C2", profession: "Policier", description: "S'assure de faire respecter la loi, intervient en cas de problème et enquête sur les infractions." },
{ dimension: "C2", profession: "Douanier", description: "Contrôle les bagages et les papiers aux frontières pour vérifier que tout est en règle." },
{ dimension: "C2", profession: "Avocat / Avocate", description: "Défend les clients devant le tribunal, prépare les dossiers et plaide pour faire respecter leurs droits." }
];

