// Placeholder questions for RIASEC test
// In a real implementation, these would be actual RIASEC questions

const questionsData = [
    { dimension: "R1", profession: "Électricien", description: "J'installe des prises et des éclairages, et je répare les pannes dans les maisons ou les usines." },
{ dimension: "R1", profession: "Technicien de maintenance", description: "Je vérifie, je répare les machines et je change les pièces défectueuses pour éviter qu'une usine ne s'arrête." },
{ dimension: "R1", profession: "Ouvrier qualifié du BTP (Maçon/Charpentier)", description: "Je construis les murs, les toits, et les fondations de bâtiments neufs ou je rénove d'anciennes structures." },
{ dimension: "R1", profession: "Ingénieur technique (Industrie)", description: "Je conçois les produits et les systèmes complexes (comme des moteurs de voiture ou des éoliennes) et j'organise leur fabrication." },
{ dimension: "R2", profession: "Architecte", description: "Je dessine les plans d'un nouveau bâtiment, je choisis les matériaux, et j'assure le suivi de la construction." },
{ dimension: "R2", profession: "Militaire / Gendarme", description: "J'assure la défense du pays, je me soumets à une discipline stricte et je participe à des opérations de sécurité ou humanitaires." },
{ dimension: "R2", profession: "Logisticien / Agent de manutention", description: "J'organise le stockage des marchandises, je gère les stocks et je veille à ce que les produits arrivent au bon endroit et à temps." },
{ dimension: "I1", profession: "Développeur web / Appli", description: "Je crée des sites internet, des applications mobiles ou des logiciels en écrivant du code." },
{ dimension: "I1", profession: "Expert en cybersécurité", description: "J'analyse les menaces informatiques et je sécurise les réseaux pour protéger les informations secrètes (des entreprises ou des États)." },
{ dimension: "I1", profession: "Chercheur scientifique", description: "Je mène des expériences en laboratoire, j'analyse des données pour faire progresser la connaissance (ex: trouver de nouveaux matériaux)." },
{ dimension: "I1", profession: "Ingénieur (Général)", description: "J'utilise mes connaissances scientifiques pour résoudre des problèmes techniques complexes dans divers domaines." },
{ dimension: "I1", profession: "Cadre / Ingénieur d'études", description: "Je participe à la conception et à la gestion de grands projets techniques et industriels (ex: dans l'aéronautique ou l'énergie)." },
{ dimension: "I2", profession: "Médecin généraliste ou spécialiste", description: "Je diagnostique les maladies, je réalise des examens, et je prescris des traitements pour soigner mes patients." },
{ dimension: "I2", profession: "Vétérinaire", description: "Je soigne les animaux (domestiques ou d'élevage), je réalise des opérations et je conseille leurs propriétaires." },
{ dimension: "I2", profession: "Dentiste / Orthodontiste", description: "Je soigne les problèmes de dents, de gencives et de mâchoire." },
{ dimension: "I2", profession: "Journaliste", description: "Je mène des enquêtes, je vérifie des informations et je rédige des articles pour informer le public." },
{ dimension: "I2", profession: "Professionnel paramédical (Kinésithérapeute/Orthopédiste/Ostéopathe)", description: "J'aide les personnes à récupérer leurs capacités physiques (mouvement, marche, élocution) après un accident ou une maladie." },
{ dimension: "I2", profession: "Cadre du BTP (Bâtiment)", description: "Je supervise les chantiers, je gère les équipes d'ouvriers et je m'assure que le travail est fait selon les normes techniques." },
{ dimension: "A1", profession: "Architecte d'intérieur", description: "Je dessine et j'aménage l'intérieur des maisons, des bureaux ou des magasins (choix des meubles, des couleurs)." },
{ dimension: "A1", profession: "Cuisinier / Cuisinière", description: "Je gère l'équipe en cuisine, je prépare les plats et je m'assure de la qualité des ingrédients." },
{ dimension: "A1", profession: "Pâtissier / Pâtissière", description: "Je crée des gâteaux et des desserts en utilisant à la fois de la technique et beaucoup de créativité." },
{ dimension: "A1", profession: "Artisan de bouche (Boucher, Charcutier, Boulanger)", description: "Je transforme les produits (viande, farine) avec mes mains pour fabriquer et vendre des aliments de qualité." },
{ dimension: "A2", profession: "Concepteur / Rédacteur (Publicité, Média)", description: "J'imagine des concepts, des slogans publicitaires ou des scénarios pour des campagnes ou des émissions." },
{ dimension: "A2", profession: "Conservateur / Conservatrice du patrimoine", description: "Je veille à la protection, à l'étude et à la mise en valeur des œuvres d'art dans les musées." },
{ dimension: "A2", profession: "Réalisateur de cinéma / Audiovisuel", description: "Je dirige les acteurs et les équipes techniques pour créer un film ou une série télévisée." },
{ dimension: "S1", profession: "Infirmier / Infirmière", description: "Je donne des soins, je prépare les médicaments et j'accompagne les patients malades ou blessés pour les rassurer." },
{ dimension: "S1", profession: "Psychologue", description: "J'écoute les gens pour comprendre leurs problèmes personnels, je les conseille et je les aide à aller mieux." },
{ dimension: "S1", profession: "Aide-soignant / Auxiliaire de vie", description: "J'aide les personnes âgées, malades ou handicapées dans leurs tâches quotidiennes (toilette, repas, déplacements)." },
{ dimension: "S1", profession: "Sage-femme", description: "J'accompagne la future mère pendant toute la grossesse, je suis l'accouchement et je m'occupe des premiers soins du bébé." },
{ dimension: "S1", profession: "Aide à domicile", description: "J'aide les personnes âgées ou dépendantes à domicile pour les tâches quotidiennes comme les courses, le ménage et les papiers administratifs." },
{ dimension: "S2", profession: "Professeur / Maître/Maîtresse", description: "Je transmets mon savoir, j'enseigne une matière et je guide les élèves pour qu'ils développent leurs compétences." },
{ dimension: "S2", profession: "Éducateur / Éducatrice spécialisé.e", description: "J'accompagne les enfants ou adultes en difficulté (sociale, handicap) pour les aider à s'intégrer ou à devenir autonomes." },
{ dimension: "S2", profession: "CPE (Conseiller principal d'éducation)", description: "Je gère l'organisation de la vie scolaire au collège ou lycée et je suis un contact important pour les élèves." },
{ dimension: "S2", profession: "Professionnel du sport / Animateur sportif", description: "J'organise des activités sportives, culturelles ou de loisirs pour un groupe et je veille à leur cohésion." },
{ dimension: "E1", profession: "Manager / Dirigeant d'équipe", description: "Je dirige et je motive une équipe d'employés pour que l'entreprise atteigne ses objectifs." },
{ dimension: "E1", profession: "Cadre administratif, comptable et financier", description: "Je supervise les services internes qui gèrent les budgets, la comptabilité et les papiers administratifs de l'entreprise." },
{ dimension: "E2", profession: "Cadre commercial / Technico-commercial", description: "J'utilise mes connaissances pour vendre des produits techniques ou des solutions complexes à d'autres entreprises." },
{ dimension: "E2", profession: "Vendeur / Vendeuse", description: "J'accueille les clients, je les conseille sur les produits et je finalise la vente." },
{ dimension: "E2", profession: "Agent immobilier", description: "Je sers d'intermédiaire pour vendre ou louer des appartements et je négocie les prix entre l'acheteur et le vendeur." },
{ dimension: "E2", profession: "Commercial", description: "Je contacte des clients pour leur vendre des produits ou des services et j'essaie d'augmenter le chiffre d'affaires." },
{ dimension: "E2", profession: "Agent de services (Hôtellerie-Restauration)", description: "J'assure l'accueil, le service et l'organisation dans un hôtel ou un restaurant." },
{ dimension: "E2", profession: "Influenceur / Youtuber / Streameur", description: "Je crée des vidéos, je publie des photos et j'interagis avec ma communauté, souvent pour vendre des produits ou des idées." },
{ dimension: "C1", profession: "Comptable", description: "Je gère les comptes, les dépenses et les recettes pour garantir l'équilibre financier de l'entreprise." },
{ dimension: "C1", profession: "Cadre administratif, comptable et financier", description: "Je supervise les services internes qui gèrent les budgets, la comptabilité et les papiers administratifs de l'entreprise." },
{ dimension: "C2", profession: "Policier / Gendarme", description: "Je fais appliquer la loi, j'assure l'ordre et la sécurité dans l'espace public et j'enquête sur les infractions." },
{ dimension: "C2", profession: "Agent d'entretien / Agent de sécurité", description: "Je nettoie des locaux en suivant des règles d'hygiène strictes ou je surveille un lieu pour assurer l'ordre et la sécurité." },
{ dimension: "C2", profession: "Pompier", description: "J'interviens rapidement sur les accidents, les incendies et les urgences médicales en respectant des procédures très précises." },
{ dimension: "C2", profession: "Avocat / Avocate", description: "Je défends mes clients devant la justice, je les conseille en droit et je plaide en leur faveur." }
];
